
stages:          # List of stages for jobs, and their order of execution
  - build
  - sonarAnalysis
  - package
  - deploy


variables:
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"
cache:
  paths:
    - .m2/repository






# Stage: Build backend
build_backend:      # This job runs in the build stage, which runs first.
  stage: build
  image: maven:3.8.4
  tags:
    - ubuntu-Demo-runner
  script:
    - cd spingboot-backend
    - echo "Building the Spring Boot application"
    - mvn clean install -DskipTests
  artifacts:
    paths:
      - target/*.jar


# Stage: Build frontend
build_frontend:
  stage: build
  before_script: 
    - npm install
  script:
    - cd angular app/app
    - npm run build --prod 
  artifacts:
    paths:
     - dist/
  only:
    - main





deploy-job:      # This job runs in the deploy stage.
  stage: deploy  # It only runs when *both* jobs in the test stage complete successfully.
  environment: production
  script:
    - echo "Deploying application..."
    - echo "Application successfully deployed."
