
stages:          # List of stages for jobs, and their order of execution
  - build
  - sonarAnalysis
  - package
  - deploy


variables:
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"
cache:
  paths:
    - .m2/repository






#Stage: Build backend
build_backend:      # This job runs in the build stage, which runs first.
  stage: build
  image: maven:3.8.4
  tags:
    - ubuntu-Demo-runner
  script:
    - cd springboot-backend
    - echo "Building the Spring Boot application"
    - mvn clean install -DskipTests
  artifacts:
    paths:
      - springboot-backend/target/*.jar


# Stage: Build frontend
#build_frontend:
 # stage: build
  #image: node:14-alpine
  #tags:
   # - ubuntu-Demo-runner
  #before_script: 
   # - ls -a 
    #- cd angular-app/app
    #- npm install
  #script:
   # - npm run build --prod 
  #artifacts:
   # paths:
    # - angular-app/app/dist/





sonarAnalysis_Backend:
  stage: sonarAnalysis
  image: sonarsource/sonar-scanner-cli:latest
  tags:
    - ubuntu-Demo-runner
  variables:
        SONAR_USER_HOME: "${CI_PROJECT_DIR}/.sonar"  # Cache SonarCloud data
  script:
    #- basename $(pwd) #command added
    #- cd $CI_PROJECT_DIR
    - sonar-scanner -X
      -Dsonar.host.url=https://sonarcloud.io/
      -Dsonar.login=ed1948d539664ac38b1d6b21b5eb122600d03516
      -Dsonar.projectKey=gitlab-demo-ci_gitlab-demo-ci-sprinboot
      -Dsonar.projectName=Gitlab_Demo_CI_Sprinboot
      -Dsonar.organization=gitlab-demo-ci
      -Dsonar.sources=./springboot-backend/src
      -Dsonar.java.binaries=./springboot-backend/target
      #-Dsonar.branch.name=$CI_COMMIT_REF_NAME
  only:
    refs:
      - master





#sonarAnalysis_Frontend:
 # stage: sonarAnalysis
  #image: sonarsource/sonar-scanner-cli:latest
  #tags:
  #  - ubuntu-Demo-runner
  #variables:
   #     SONAR_USER_HOME: "${CI_PROJECT_DIR}/.sonar"  # Cache SonarCloud data
  #script:
    #- basename $(pwd) #command added
    #- cd $CI_PROJECT_DIR
   # - sonar-scanner -X
    #  -Dsonar.host.url:$SONAR_HOST_URL 
     # -Dsonar.login=ed1948d539664ac38b1d6b21b5eb122600d03516
      #-Dsonar.projectKey=gitlab-demo-ci_3tier-frontend-angular
      #-Dsonar.projectName=3tier_Frontend_Angular
      #-Dsonar.organization:$SONAR_ORGANIZATION
      #-Dsonar.sources=./angular-app/app/src
      
      #-Dsonar.branch.name=$CI_COMMIT_REF_NAME
  #only:
   # refs:
    #  - master
  

package:
  stage: package
  tags:
    - ubuntu-Demo-runner
  script:
    - cd springboot-backend
    - echo "packging application"
    - mvn package -DskipTests
  artifacts:
    paths:
      - springboot-backend/target/*.jar



#deploy-job:      # This job runs in the deploy stage.
#  stage: deploy
 # tags:
  #  - ubuntu-Demo-runner # It only runs when *both* jobs in the test stage complete successfully.
  #environment: production
  #script:
   # - echo "Deploying application..."
    #- echo "Application successfully deployed."
